[package]
name = "rust-simple_web_browser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
spinners = "4.1.0"
html_parser = "0.6.3"
ncurses = "5.101.0"
